version: "3.8"
name: furniture-store

services:
  app:
    build:
#      args:
#        user: roth
#        uid: 1000
      context: ./
      dockerfile: Dockerfile
#    working_dir: /var/www/
#    volumes:
#      - ./:/var/www
    networks:
      - furniture-store
    depends_on:
        - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /var/mysql:/docker-entrypoint-initdb.d
    networks:
      - furniture-store

  nginx:
    build:
      context: ./docker-compose/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
#      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - furniture-store
    depends_on:
        - app

networks:
  furniture-store:
    driver: bridge
